[general]

# import catpuccin theme
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[window]

dimensions = { columns = 117, lines = 31 }
padding = { x = 0, y = 0 }

#opacity = 0.95
#blur = true

decorations = "Full"
title = "Terminal"
dynamic_title = true

[font]

normal = {family = "MesloLGMDZ Nerd Font Mono", style = "Regular"}
size = 10.5


[env]

TERM = "xterm-256color"

